framework: jasmine
preRun:
     command:
        - yarn install
preMerge:
  pattern:
    - "./scripts/generate_cloudbuild_test.js"
    - "./scripts/run_flaky_test.js"
postMerge:
  pattern: 
    - "./scripts/generate_cloudbuild_test.js"
    - "./scripts/run_flaky_test.js"
postRun:
     command:
        - yarn --version
version: 1.0
